### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by LinuxUserGD**
Fixes invalid unicode characters reported by Gitea/Forgejo (see [go-gitea/gitea#23682](https://www.github.com/go-gitea/gitea/issues/23682))

screenshot

### CODE REVIEW

**Comment by jirutka** [comment]
Are you trolling me? These are completely valid Unicode characters.

**Comment by LinuxUserGD** [comment]
> Are you trolling me? These are completely valid Unicode characters.

Sorry for the typo PR, according to online ASCII validators `it’s` instead of `it's` is invalid though.
<https://onlinetools.com/ascii/validate-ascii>

qemu

**Comment by jirutka** [comment]
> Sorry for the typo PR

If you mean typo as typography, then your PR is literally degrading the typography in this document.

> according to online ASCII validators it’s instead of it's is invalid though.

It’s not 70s anymore, we live in the 21st century, where Unicode is the standard. So I’m using proper Unicode punctuation characters (e.g. [U+2019](https://www.compart.com/en/unicode/U+2019)) instead of their poor ASCII replacements.

If you don’t understand what I’m saying, then I’m sorry, you need to learn something about typography and Unicode.

**Comment by LinuxUserGD** [comment]
> It’s not 70s anymore, we live in the 21st century, where Unicode is the standard. So I’m using proper Unicode punctuation characters (e.g. [U+2019](https://www.compart.com/en/unicode/U+2019)) instead of their poor ASCII replacements.

According to the [AsciiDoc documentation](https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/), the ASCII substitution for the typographic apostrophe is `&#8217;` which would be displayed correctly as well (see https://github.com/LinuxUserGD/setup-alpine/commit/57078161374d10b9e0130ec14a2378bb589c71c3 for reference).

**Pull request closed without merging**
